// Auto-generated by build.rs - do not edit

pub const VERSION: &str = "0.0.0";
pub const COMMIT_HASH: &str = "16895973";
pub const COMMITS_SINCE_TAG: u32 = 1;
pub const HAS_UNCOMMITTED: bool = false;

pub fn version_string() -> String {
    let mut version = VERSION.to_string();
    
    if COMMITS_SINCE_TAG > 0 {
        version.push_str("+dev");
    }
    
    if HAS_UNCOMMITTED {
        version.push_str("+dirty");
    }
    
    let mut commit = format!("commit: {}", COMMIT_HASH);
    if HAS_UNCOMMITTED {
        commit.push_str("+dirty");
    }
    
    format!("{} ({})", version, commit)
}
